CREATE DATABASE IF NOT EXISTS archdb;
USE archdb;

CREATE TABLE User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(255) UNIQUE NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  birth_date DATE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(255),
  password VARBINARY(255) NOT NULL,
  photo BLOB
);

CREATE TABLE Wall (
  wall_id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  user_id INT,
  description TEXT,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE Messages (
  message_id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  author_id INT,
  recipient_id INT,
  message_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (recipient_id) REFERENCES User(id) ON DELETE CASCADE
);

